{% set name = "dtool_lookup_server_direct_mongo_plugin" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/dtool-lookup-server-direct-mongo-plugin/dtool-lookup-server-direct-mongo-plugin-{{ version }}.tar.gz
  sha256: 827e6f358d4f5322f298ecee488c45ab12c745be00fd2bc6cd072aca20b25c75

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools_scm
    - setuptools
  run:
    - dtool_lookup_server >=0.17.2
    - dtoolcore >=3.17.0
    - python >={{ python_min }}

test:
  imports:
    - dtool_lookup_server_direct_mongo_plugin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IMTEK-Simulation/dtool-lookup-server-direct-mongo-plugin
  summary: This plugin allows to submit mongo queries and aggregation pipelines directly to the lookup servers underlying MongoDB.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
